### ISSUE TITLE
How to process SemEval raw text?

### ISSUE THREAD

**Issue by lujiaying** [INK-USC/NERO#4]
Hi,

Thank you for sharing the code. It is helpful to replicate your result.
I just wondering how is the pipeline to pre-processing SemEval raw text? As I know, SemEval does not provide `Subj/Obj` information. 
According to https://github.com/INK-USC/NERO/issues/2#issuecomment-582695502, it seems that `Subj/Obj` are generated from dep parser results. But I am not quite clear how to get `"subj_type": "O", "subj_pst":[], "subj_start":1, "subj_end":1` information.

Thanks!

**Comment by wzhouad** [comment]
Hi,

When I wrote the paper, I used data processed by others. I write this [script](https://www.dropbox.com/s/giozfj0ifnx7p0o/semeval_prepro.py?dl=0) to process the SemEval training data. Its result may be different from the paper because of different NLP processor. You can also access the processed SemEval data [here](https://www.dropbox.com/s/rtvn2c4wej80jxw/semeval.zip?dl=0).

**Comment by lujiaying** [comment]
Thanks very much for sharing the script and processed corpus.
